# Generated by Django 4.2.1 on 2023-05-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'անձնական էջ', 'verbose_name_plural': 'անձնական էջեր'},
        ),
        migrations.AlterModelOptions(
            name='stockuser',
            options={'verbose_name': 'Օգտատեր', 'verbose_name_plural': 'Օգտատերեր'},
        ),
        migrations.AlterField(
            model_name='stockuser',
            name='is_stock_user',
            field=models.BooleanField(default=True, verbose_name='Stock User'),
        ),
    ]
