# Generated by Django 4.2.1 on 2023-05-29 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ստեղծվել է')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='փոփոխվել է')),
                ('name', models.CharField(max_length=255, verbose_name='անվանում')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ստեղծող')),
            ],
            options={
                'verbose_name': 'Չափման միավոր',
                'verbose_name_plural': 'Չափման միավորներ',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Դասակարգ', 'verbose_name_plural': 'Դասակարգեր'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Ենթադասակարգ', 'verbose_name_plural': 'Ենթադասակարգեր'},
        ),
        migrations.AlterField(
            model_name='category',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ստեղծող'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ստեղծվել է'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, default='images/no_image.png', null=True, upload_to='images/categories/icons/', verbose_name='պատկեր'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='անվանում'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='փոփոխվել է'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ստեղծող'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='դասակարգ'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ստեղծվել է'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.ImageField(blank=True, default='images/no_image.png', null=True, upload_to='images/subcategories/icons/', verbose_name='պատկեր'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='անվանում'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='փոփոխվել է'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ստեղծվել է')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='փոփոխվել է')),
                ('as_key', models.CharField(blank=True, max_length=30, null=True, verbose_name='ՀԾ Կոդ')),
                ('p_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='Գործարանային համար')),
                ('name', models.CharField(max_length=300, verbose_name='Անվանում')),
                ('image', models.ImageField(blank=True, default='images/no_image.png', null=True, upload_to='images/products/', verbose_name='Նկար')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Քանակ')),
                ('critical_quantity', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=10, null=True, verbose_name='Մինիմալ քանակ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Առկայություն')),
                ('in_use', models.BooleanField(default=False, verbose_name='Օգտագործման մեջ է')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Նկարագրություն')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ստեղծող')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Դասակարգ')),
                ('measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.measure', verbose_name='Չ/Մ')),
                ('stockroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.stockroom', verbose_name='պահեստախուց')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory', verbose_name='Ենթադասակարգ')),
            ],
            options={
                'verbose_name': 'Ապրանք',
                'verbose_name_plural': 'Ապրանքներ',
            },
        ),
    ]
