# Generated by Django 4.2.1 on 2023-05-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name': 'Հաշվիչ', 'verbose_name_plural': 'Հաշվիչ'},
        ),
        migrations.AddField(
            model_name='counter',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
