# Generated by Django 4.2.1 on 2023-05-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_counter_options_counter_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
