# Generated by Django 4.2.1 on 2023-05-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Ընդամենը ելքերի քանակ'),
        ),
        migrations.AddField(
            model_name='product',
            name='out_count',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10, verbose_name='Ընդամենը դուրսգրված քանակ'),
        ),
    ]
